### ISSUE TITLE
Composer deprecation

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-base-sent-email#1]
I don't even have this installed, but seems to be bundled with Sprout Forms - the only Sprout plugin I have installed.

Getting the following when `composer update`-ing.

```
Deprecation Notice: Class barrelstrength\sproutbasesentemail\web\assets\email\SentEmailAsset located in ./vendor/barrelstrength/sprout-base-sent-email/src/web/assets/sentemail/SentEmailAsset.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
```

**Comment by BenParizek** [comment]
This will be resolved in the next major release of Sprout Forms and any other plugins using this module. We'll be reverting to a single `sprout-base` dependency.

**Comment by BenParizek** [comment]
This has been updated in v1.1.3
